AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'db/schema.rb'
    - 'spec/support/**/*'
    - 'config/application.rb'
    - 'vendor/**/*'

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Metrics/LineLength:
  Max: 100

CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/BlockLength:
  ExcludedMethods:
    - "describe"
    - "context"
    - "shared_context"

Documentation:
  Enabled: false
