Style/FileName:
  Exclude:
    - 'lib/mes-elastic.rb'

Style/BracesAroundHashParameters:
  Exclude:
    - 'spec/**/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'spec/**/*'

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/LineLength:
  Max: 100
