version: '2'
services:
  app:
    build: .
    volumes:
      - .:/app
      - $HOME/.aws:/root/.aws:ro
      - $HOME/.ssh:/root/.ssh:ro
    command: bundle exec rspec
    links:
      - eva_elasticsearch
      - mes_elasticsearch

  eva_elasticsearch:
    image: elasticsearch:1.5.2
    ports:
      - 9200

  mes_elasticsearch:
    image: elasticsearch:1.5.2
    ports:
      - 9200
