version: '2'
volumes:
  bundle:
services:
  app:
    build: .
    volumes:
      - .:/app
      - bundle:/bundle
    environment:
      - BUNDLE_PATH=/bundle
    working_dir: /app
    command: bundle exec rspec
    links:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms250m -Xmx250m"
