version: '2'
services:
  app:
    image: 979514658570.dkr.ecr.eu-west-1.amazonaws.com/mes-base-image:0.24
    volumes:
      - .:/app
      - .bundle:/bundle
      - $HOME/.aws:/root/.aws:ro
    command: bundle exec rspec
    links:
      - eva-elasticsearch
      - mes-elasticsearch
      - content-api-elasticsearch

  eva-elasticsearch:
    command: -Des.cluster.name="eva"
    image: elasticsearch:2.3
    ports:
      - 9200

  mes-elasticsearch:
    command: -Des.cluster.name="mes"
    image: elasticsearch:2.3
    ports:
      - 9200

  content-api-elasticsearch:
    command: -Des.cluster.name="content-api"
    image: elasticsearch:2.3
    ports:
      - 9200
