version: '2'
services:
  app:
    image: 979514658570.dkr.ecr.eu-west-1.amazonaws.com/mes-base-image:0.24
    volumes:
      - .:/app
      - .bundle:/bundle
      - $HOME/.aws:/root/.aws:ro
    command: bundle exec rspec
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    environment:
      - xpack.security.enabled=false
    ports:
      - 9200
