version: '2'
services:
  app:
    build: .
    volumes:
      - .:/app
      - $HOME/.aws:/root/.aws:ro
      - $HOME/.ssh:/root/.ssh:ro
    command: bundle exec rspec
    links:
      - eva-elasticsearch
      - mes-elasticsearch

  eva-elasticsearch:
    command: -Des.cluster.name="eva"
    image: elasticsearch:2.3
    ports:
      - 9200

  mes-elasticsearch:
    command: -Des.cluster.name="mes"
    image: elasticsearch:2.3
    ports:
      - 9200
