version: '2'
services:
  app:
    image: 979514658570.dkr.ecr.eu-west-1.amazonaws.com/mes-base-image:0.24
    volumes:
      - .:/app
      - .bundle:/bundle
      - $HOME/.aws:/root/.aws:ro
    command: bundle exec rspec
    depends_on:
      - eva-elasticsearch
      - mes-elasticsearch
      - content-api-elasticsearch

  eva-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    environment:
      - cluster.name=eva
      - xpack.security.enabled=false
    ports:
      - 9200

  mes-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    environment:
      - cluster.name=mes
      - xpack.security.enabled=false
    ports:
      - 9200

  content-api-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    environment:
      - cluster.name=content-api
      - xpack.security.enabled=false
    ports:
      - 9200
