version: '2'
volumes:
  bundle:
services:
  app:
    image: 979514658570.dkr.ecr.eu-west-1.amazonaws.com/mes-base-image:0.24
    volumes:
      - .:/app
      - bundle:/bundle
      - $HOME/.aws:/root/.aws:ro
    command: bundle exec rspec
    links:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
